### ISSUE TITLE
[Task] 브랜드 더미데이터 작성

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#110]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] 브랜드 brand_id, _id 정리
2. [x] 브랜드 로고 자료모음
3. [ ] 각종 정보 인사이트 모음

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
