### ISSUE TITLE
[Task] 마이페이지 기능 추가 

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#111]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [ ]  마이페이지 브랜드 추가
2. [ ]  마이페이지 브랜드 삭제
3. [ ]  로그인 할경우만 사용가능 구현

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
