### ISSUE TITLE
[Client] React-redux 기본 파일 생성 및 가이드 작성

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#14]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] React-redux 생성
2. [x] Action, Reducer, Store 작성
3. [x] 예시 가이드 작성 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
