### ISSUE TITLE
[Client] Task 분배 및  SR 마무리

### ISSUE THREAD

**Issue by xxrealsw** [codestates/Bransome-client#25]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: Task 분배 

### TODO
1. [x] Task 분배
2. [x] 설문조사 완료, 피드백 
3. [x] UI 기본틀 잡기
4. [x] 새로운 스택 스터디

1.home (상)  : 홍성현
2.brand (상) : 박선아
3.brandInfo (상) : 이상운
4.mypage (중) : 홍성현
5.Best20 (상) : 이상운
6.modal(social Login,mypage, Logout)) (중) : 박선아, 이상운, 홍성현

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
