### ISSUE TITLE
[Task] Home 메인페이지 구성

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#26]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] 메인페이지 레이아웃 및 반응형 디자인
2. [x] AOS 라이브러리를 이용한 스크롤 에니메이션 효과 구현
3. [x] 검색창 구현
4. [x] redux 스터디
5. [x] react-redux 활용하기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
