### ISSUE TITLE
[Task] React-Route를 활용해 Navigation Bar구현

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#29]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] React-Router를 사용해 <Route Path="" component={} /> 활용
2. [x] 브랜드 페이지 연결
3. [x] BEST 페이지 연결

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
