### ISSUE TITLE
[Task] Navigation 디자인

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#34]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] Brand, Best20 Nav link를 클릭하면 각 화면을 보여주는 기능 구현
2. [x] 팀원과 구성한 색상에 맞춰 css Styling
3. [x] 로그인, 소셜로그인, 회원가입 버튼 제작

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
