### ISSUE TITLE
[Task] 홈화면 캐로셀 구현

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#44]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] 정보를 담은 캐로셀 구현
2. [x] 왼쪽으로 가는 슬라이드 버튼 구현
3. [x] 오른쪽으로 가는 슬라이드 버튼 구현
4. [x] 가운데에 현재 페이지 보여주는 기능 구현

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
