### ISSUE TITLE
[Task] Home 리뷰 페이지 구현

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#45]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] 후기 페이지 fakeData 구현
2. [x] 애니메이션 (스크롤 AOS) 탑재
3. [x] map을 사용하여 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
