### ISSUE TITLE
[Task] 로그인 모달 창 구현

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#64]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] 로그인 모달 실행시 에니메이션 효과 적용
2. [x] 모달 종료 버튼 달기
3. [x] 키입력, 반투명한 백그라운드 클릭시 모달 닫기

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
