### ISSUE TITLE
[Task] Mypage 프로필구현

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#78]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] 프로필 이미지 구현
2. [x] 프로필 정보(이메일, 유저네임) 화면 출력 구현
3. [x] 로그아웃 버튼 구현

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
