### ISSUE TITLE
[Task] Mypage 추가한 브랜드 보여주는 기능 구현

### ISSUE THREAD

**Issue by ghost** [codestates/Bransome-client#79]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [ ] 브랜드 추가된 목록 보여주기 구현
2. [ ] 브랜드 삭제 기능 구현
3. [ ] 추가한 브랜드가 사이즈 초과시 줄어드는 효과 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
